<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AvaloniaMvvmExpressVersion>1.0.1</AvaloniaMvvmExpressVersion>
  </PropertyGroup>
</Project>
